[versions]
blossom = "2.1.0"
jvmdowngrader = "1.2.2"
netty = "4.1.128.Final"
spotless = "7.0.3"
shadow = "9.0.0-beta13"
unimined = "1.3.14"

[libraries]
annotations = { group = "org.jetbrains", name = "annotations", version = "26.0.2" }
asm-tree = { group = "org.ow2.asm", name = "asm-tree", version = "6.2" }
brigadier = { group = "com.mojang", name = "brigadier", version = "1.0.18" }
guava = { group = "com.google.guava", name = "guava", version = "33.3.1-jre" }
gson = { group = "com.google.code.gson", name = "gson", version = "2.13.2" }
ignite-api = { group = "space.vectrix.ignite", name = "ignite-api", version = "1.1.0" }
jspecify = { group = "org.jspecify", name = "jspecify", version = "1.0.0" }
mixin = { group = "org.spongepowered", name = "mixin", version = "0.8.5-SNAPSHOT" }
mojang-authlib = { group = "com.mojang", name = "authlib", version = "7.0.61" }
netty-buffer = { group = "io.netty", name = "netty-buffer", version.ref = "netty" }
netty-codec = { group = "io.netty", name = "netty-codec", version.ref = "netty" }
slf4j = { group = "org.slf4j", name = "slf4j-api", version = "2.0.16" }

[plugins]
blossom = { id = "net.kyori.blossom", version.ref = "blossom" }
jvmdowngrader = { id = "xyz.wagyourtail.jvmdowngrader", version.ref = "jvmdowngrader" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
unimined = { id = "xyz.wagyourtail.unimined", version.ref = "unimined" }
